[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "flask-oasis"
version = "0.1.dev0"
dependencies = ["flask", "Zangar @ git+https://github.com/Dog-Egg/Zangar"]
